apiVersion: v1
kind: Service
metadata:
  name: pod-identity-webhook
  namespace: default
  annotations:
    prometheus.io/port: "443"
    prometheus.io/scheme: "https"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: pod-identity-webhook
