apiVersion: v1
kind: Service
metadata:
  name: pod-identity-webhook
  namespace: default
  annotations:
    prometheus.io/port: "9999"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 443
    - name: metrics
      port: 9999
      targetPort: 9999
  selector:
    app: pod-identity-webhook
