# Use the standard Amazon Linux base, provided by ECR/KaOS
# This is a placeholder, replaced by the `DockerFileBuild` build system.
# It will point to the standard shared Amazon Linux image, with a versioned tag.
FROM AMAZON_LINUX

# relative to your build directory
COPY gopath/bin/linux_amd64/amazon-eks-pod-identity-webhook /webhook
