name: test

on: pull_request
jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'aws/amazon-eks-pod-identity-webhook'
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Version
      run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go mod tidy && go mod vendor && go test ./...
